version: '3'
services:
  post_db:
    image: mongo:${VERSION_MONGODB}
    volumes:
      - post_db:/data/db
    networks:
      - reddit
  ui:
    image: ${USERNAME}/ui:${VERSION_UI}
    ports:
      - ${PORT}:${PORT}/tcp
    networks:
      - reddit
    environment:
      - POST_SERVICE_HOST=post
      - POST_SERVICE_PORT=5000
      - COMMENT_SERVICE_HOST=comment
      - COMMENT_SERVICE_PORT=9292
    depends_on:
      - post
    logging:
        driver: "fluentd"
        options:
          fluentd-address: localhost:24224
          tag: service.ui

  post:
    image: ${USERNAME}/post:${VERSION_POST}
    networks:
      - reddit
    environment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post

  comment:
    image: ${USERNAME}/comment:${VERSION_COMMENT}
    networks:
      - reddit

volumes:
  post_db:

networks:
  reddit:
