version: '3'
services:
  post_db:
    image: mongo:${VERSION_MONGODB}
    volumes:
      - post_db:/data/db
    back_net:
        aliases:
          - comment_db
          - post_ db
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${VERSION_UI}
    ports:
      - {$PORT}:{$PORT}/tcp
    networks:
      - reddit
  post:
    build: ./post-py
    image: ${USERNAME}/post:{$VERSION_POST}
    networks:
      - reddit
  comment:
    build: ./comment
    image: ${USERNAME}/comment:{$VERSION_COMMENT}
    networks:
      - reddit

volumes:
  post_db:

networks:
  reddit:
